on: [push]

jobs:
  ecr:
    environment: test
    runs-on: ubuntu-latest
    name: Docker build and push to ECR
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Exemple of build using docker
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Docker Build
        env:
            ECR_REPOSITORY: 'junk1'
        run: |
            docker build --pull -t ${{ secrets.CONTAINER_REGISTRY_HOST }}/$ECR_REPOSITORY:latest .
            docker push ${{ secrets.CONTAINER_REGISTRY_HOST }}/$ECR_REPOSITORY:latest
          
