on: [push]

jobs:
  ecr:
    environment: test
    runs-on: ubuntu-latest
    name: Docker build and push to ECR
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Exemple of build using docker
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Docker Build
        env:
            ECR_REPOSITORY: 'junk1'
            # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
            docker build --pull -t ${{ secrets.CONTAINER_REGISTRY_HOST }}/$ECR_REPOSITORY:latest .
            docker push ${{ secrets.CONTAINER_REGISTRY_HOST }}/$ECR_REPOSITORY:latest
          
